package com.mina.moonchat.viewmodels

import android.app.Application
import android.util.Log
import androidx.lifecycle.LiveData
import androidx.lifecycle.MutableLiveData
import androidx.lifecycle.viewModelScope
import androidx.paging.ExperimentalPagingApi
import androidx.paging.Pager
import androidx.paging.PagingConfig
import androidx.paging.PagingData
import androidx.paging.cachedIn
import androidx.paging.map
import com.mina.moonchat.application.MoonChat
import com.mina.moonchat.base.BaseViewModel
import com.mina.moonchat.data.dto.toTextMessage
import com.mina.moonchat.data.server.ChatRemoteMediator
import com.mina.moonchat.data.server.ServerSide
import com.mina.moonchat.data.server.UserLocalRepository
import com.mina.moonchat.models.TextMessage
import com.mina.moonchat.models.User
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.map
import kotlinx.coroutines.launch
import java.util.Date

class ChatViewModel(app: Application) : BaseViewModel(
    app,
    (app as MoonChat).repository,
    (app as MoonChat).repo
) {
    companion object {
        private const val TAG = "ChatViewModel"
    }

    private val repository: UserLocalRepository = (app as MoonChat).repo

    // UI State
    val textMessage = MutableLiveData<String>()
    val username = MutableLiveData<String>()

    // Error state
    private val _errorMessage = MutableLiveData<String?>()
    val errorMessage: LiveData<String?> = _errorMessage

    // Loading state
    private val _isSending = MutableLiveData<Boolean>()
    val isSending: LiveData<Boolean> = _isSending

    // Track current chat for cleanup
    private var currentRecipientId: String? = null

    /**
     * Get message stream for a chat
     * This combines Room + Firebase pagination
     */
    fun getMessageStream(recipientId: String): Flow<PagingData<TextMessage>> {
        currentRecipientId = recipientId
        val currentUserId = mAuth.currentUser?.uid ?: throw IllegalStateException("User not logged in")

        // Start real-time sync
        repository.activateRealtimeSync(currentUserId, recipientId)

        return repository.getChatStream(currentUserId, recipientId)
            .cachedIn(viewModelScope)
    }

    /**
     * Stop real-time sync when leaving chat
     */
    fun stopSync() {
        currentRecipientId?.let { recipientId ->
            mAuth.currentUser?.uid?.let { currentUserId ->
                repository.stopRealtimeSync(currentUserId, recipientId)
            }
        }
    }

    /**
     * Handle send button click
     */
    fun onSendClicked(recipientUser: User, messageText: String) {
        if (messageText.isBlank()) return

        val senderId = mAuth.currentUser?.uid ?: run {
            _errorMessage.value = "User not logged in"
            return
        }

        _isSending.value = true

        getCurrentUserInfo { currentUser ->
            val newMessage = TextMessage(
                id = "", // Will be generated by Firebase
                text = messageText.trim(),
                senderId = senderId,
                recipientId = recipientUser.userId,
                senderName = currentUser.displayName ?: "",
                recipientName = recipientUser.displayName ?: "",
                date = Date(),
                channelId = repository.getChannelId(senderId, recipientUser.userId),
                status = "PENDING",
                isRead = false
            )

            viewModelScope.launch {
                try {
                    repository.sendMessage(newMessage)
                    Log.d("TAG", "Message sent successfully")
                    textMessage.value = "" // Clear input
                } catch (e: Exception) {
                    Log.e("TAG", "Failed to send message: ${e.message}")
                    _errorMessage.value = "Failed to send message"
                } finally {
                    _isSending.value = false
                }
            }
        }
    }

    /**
     * Retry sending a failed message
     */
    fun retryMessage(message: TextMessage) {
        viewModelScope.launch {
            try {
                repository.retryMessage(message)
                Log.d(TAG, "Message retry initiated")
            } catch (e: Exception) {
                Log.e(TAG, "Failed to retry message: ${e.message}")
                _errorMessage.value = "Failed to retry message"
            }
        }
    }

    /**
     * Mark messages as read
     */
    fun markMessagesAsRead(recipientId: String) {
        viewModelScope.launch {
            try {
                val currentUserId = mAuth.currentUser?.uid ?: return@launch
                val channelId = repository.getChannelId(currentUserId, recipientId)
                repository.markMessagesAsRead(channelId, currentUserId)
            } catch (e: Exception) {
                Log.e(TAG, "Failed to mark messages as read: ${e.message}")
            }
        }
    }

    /**
     * Clear error message
     */
    fun clearError() {
        _errorMessage.value = null
    }

    /**
     * Sync pending messages on startup
     */
    fun syncPendingMessages() {
        viewModelScope.launch {
            try {
                repository.syncPendingMessages()
            } catch (e: Exception) {
                Log.e(TAG, "Failed to sync pending messages: ${e.message}")
            }
        }
    }

    override fun onCleared() {
        super.onCleared()
        stopSync()
    }
}